CREATE TABLE property_details_next (
  property_id TEXT PRIMARY KEY NOT NULL,
  usable_area_m2 REAL,
  built_area_m2 REAL,
  plot_area_m2 REAL,
  floor TEXT,
  building_floors INTEGER,
  parking_spaces INTEGER,
  balcony_count INTEGER,
  terrace_count INTEGER,
  year_built INTEGER,
  condition TEXT CHECK(condition IN ('new_build', 'excellent', 'good', 'needs_renovation')),
  heating TEXT CHECK(heating IN ('central', 'underfloor', 'electric', 'heat_pump', 'gas_boiler', 'none')),
  energy_rating TEXT CHECK(energy_rating IN ('A+', 'A', 'B', 'B-', 'C', 'D')),
  orientation TEXT,
  exterior INTEGER,
  elevator INTEGER,
  storage_room INTEGER,
  built_in_wardrobes INTEGER,
  equipped_kitchen INTEGER,
  furnished INTEGER,
  accessibility_adapted INTEGER,
  guest_bathrooms INTEGER,
  monthly_condo_fee_eur REAL,
  bathrooms_full INTEGER,
  FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE
);

INSERT INTO property_details_next (
  property_id,
  usable_area_m2,
  built_area_m2,
  plot_area_m2,
  floor,
  building_floors,
  parking_spaces,
  balcony_count,
  terrace_count,
  year_built,
  condition,
  heating,
  energy_rating,
  orientation,
  exterior,
  elevator,
  storage_room,
  built_in_wardrobes,
  equipped_kitchen,
  furnished,
  accessibility_adapted,
  guest_bathrooms,
  monthly_condo_fee_eur,
  bathrooms_full
)
SELECT
  property_id,
  usable_area_m2,
  built_area_m2,
  plot_area_m2,
  floor,
  building_floors,
  parking_spaces,
  balcony_count,
  terrace_count,
  year_built,
  condition,
  heating,
  energy_rating,
  orientation,
  exterior,
  elevator,
  storage_room,
  built_in_wardrobes,
  equipped_kitchen,
  furnished,
  accessibility_adapted,
  guest_bathrooms,
  monthly_condo_fee_eur,
  bathrooms_full
FROM property_details;

DROP TABLE property_details;
ALTER TABLE property_details_next RENAME TO property_details;
