import type { ListingFeature, ListingMode, PropertyListing } from "./types";

function buildGoogleMapsUrl(latitude: number, longitude: number): string {
  return `https://www.google.com/maps/search/?api=1&query=${latitude},${longitude}`;
}

const featureLabels: Record<ListingFeature, string> = {
  sea_view: "Вид на море",
  city_center: "Центр города",
  parking: "Паркинг",
  pool: "Бассейн",
  security: "Охраняемая территория",
  furnished: "С мебелью",
  balcony: "Балкон",
  terrace: "Терраса",
};

export const propertyListings: PropertyListing[] = [
  {
    id: "irina-001",
    slug: "cascais-ocean-villa-irina-001",
    mode: "sale",
    title: "Вилла с панорамой на океан",
    city: "Кашкайш",
    district: "Guia",
    country: "Португалия",
    location: {
      addressLabel: "Guia, Cascais, Portugal",
      latitude: 38.6998,
      longitude: -9.4212,
      googleMapsUrl: buildGoogleMapsUrl(38.6998, -9.4212),
    },
    priceAmount: 1850000,
    priceLabel: "€1 850 000",
    shortDescription:
      "4 спальни, приватный сад и терраса для клиентов, которые ищут спокойный адрес рядом с океаном.",
    fullDescription:
      "Современная вилла в тихом жилом квартале Кашкайша. Подходит для постоянного проживания или семейной резиденции у океана. Просторная дневная зона открывается на террасу и бассейн, а приватный блок спален ориентирован на утреннее солнце.",
    bedrooms: 4,
    bathrooms: 3,
    areaM2: 286,
    imageUrl:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["sea_view", "pool", "parking", "terrace", "security"],
    details: {
      propertyType: "villa",
      usableAreaM2: 248,
      builtAreaM2: 286,
      plotAreaM2: 620,
      floor: "Дом целиком",
      exterior: true,
      elevator: false,
      parkingSpaces: 2,
      storageRoom: true,
      builtInWardrobes: true,
      equippedKitchen: true,
      furnished: false,
      balconyCount: 1,
      terraceCount: 2,
      condition: "excellent",
      yearBuilt: 2021,
      heating: "underfloor",
      accessibilityAdapted: false,
      orientation: ["юг", "запад"],
      energyRating: "A",
      bathroomsFull: 3,
      guestBathrooms: 1,
      buildingFloors: 2,
      monthlyCondoFeeEur: 0,
    },
    transportAccess: [
      { mode: "bus", route: "1623", stopName: "Guia Centro", walkMinutes: 6 },
      { mode: "bus", route: "417", stopName: "Casa da Guia", walkMinutes: 8 },
      { mode: "train", route: "Linha de Cascais", stopName: "Cascais", walkMinutes: 18 },
    ],
    taxProfile: {
      propertyTransferTaxRate: 0.065,
      stampDutyRate: 0.008,
      notaryEstimateRate: 0.012,
    },
    agentName: "Ирина",
    publishedAt: "2026-04-25",
  },
  {
    id: "irina-002",
    slug: "lisbon-design-apartment-irina-002",
    mode: "sale",
    title: "Апартаменты в Лиссабоне",
    city: "Лиссабон",
    district: "Avenidas Novas",
    country: "Португалия",
    location: {
      addressLabel: "Avenidas Novas, Lisbon, Portugal",
      latitude: 38.7374,
      longitude: -9.1502,
      googleMapsUrl: buildGoogleMapsUrl(38.7374, -9.1502),
    },
    priceAmount: 690000,
    priceLabel: "€690 000",
    shortDescription:
      "2 спальни, высокий этаж, светлая гостиная и удобная локация для жизни или инвестиции.",
    fullDescription:
      "Апартаменты после обновления с удобной планировкой, встроенным хранением и солнечной гостиной. Район хорошо подходит для деловой активности, долгосрочной аренды и комфортной городской жизни.",
    bedrooms: 2,
    bathrooms: 2,
    areaM2: 118,
    imageUrl:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["city_center", "parking", "furnished", "balcony"],
    details: {
      propertyType: "apartment",
      usableAreaM2: 104,
      builtAreaM2: 118,
      floor: "7 этаж",
      exterior: true,
      elevator: true,
      parkingSpaces: 1,
      storageRoom: true,
      builtInWardrobes: true,
      equippedKitchen: true,
      furnished: true,
      balconyCount: 1,
      terraceCount: 0,
      condition: "excellent",
      yearBuilt: 2018,
      heating: "central",
      accessibilityAdapted: true,
      orientation: ["восток", "юг"],
      energyRating: "B",
      bathroomsFull: 2,
      buildingFloors: 10,
      monthlyCondoFeeEur: 145,
    },
    transportAccess: [
      { mode: "metro", route: "Azul", stopName: "São Sebastião", walkMinutes: 5 },
      { mode: "bus", route: "726", stopName: "Avenidas Novas", walkMinutes: 4 },
      { mode: "train", route: "Sintra", stopName: "Entrecampos", walkMinutes: 11 },
    ],
    taxProfile: {
      propertyTransferTaxRate: 0.06,
      stampDutyRate: 0.008,
      notaryEstimateRate: 0.011,
    },
    agentName: "Ирина",
    publishedAt: "2026-04-23",
  },
  {
    id: "irina-003",
    slug: "porto-riverside-loft-irina-003",
    mode: "rent",
    title: "Лофт у набережной Дору",
    city: "Порту",
    district: "Ribeira",
    country: "Португалия",
    location: {
      addressLabel: "Ribeira, Porto, Portugal",
      latitude: 41.1406,
      longitude: -8.611,
      googleMapsUrl: buildGoogleMapsUrl(41.1406, -8.611),
    },
    priceAmount: 2400,
    priceLabel: "€2 400 / месяц",
    shortDescription:
      "Атмосферный лофт для аренды с открытой зоной кухни-гостиной и пешей доступностью к центру.",
    fullDescription:
      "Лофт для долгосрочной аренды с характерной архитектурой, высокими потолками и открытым пространством. Подойдет для пары или специалиста, которому важны стиль, центр города и быстрый доступ к инфраструктуре.",
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 84,
    imageUrl:
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["city_center", "furnished", "balcony"],
    details: {
      propertyType: "loft",
      usableAreaM2: 78,
      builtAreaM2: 84,
      floor: "2 этаж",
      exterior: true,
      elevator: false,
      parkingSpaces: 0,
      storageRoom: false,
      builtInWardrobes: false,
      equippedKitchen: true,
      furnished: true,
      balconyCount: 1,
      terraceCount: 0,
      condition: "good",
      yearBuilt: 2009,
      heating: "electric",
      accessibilityAdapted: false,
      orientation: ["запад"],
      energyRating: "C",
      bathroomsFull: 1,
      buildingFloors: 4,
      monthlyCondoFeeEur: 90,
    },
    transportAccess: [
      { mode: "tram", route: "1", stopName: "Infante", walkMinutes: 3 },
      { mode: "bus", route: "500", stopName: "Ribeira", walkMinutes: 2 },
      { mode: "train", route: "Urbanos do Porto", stopName: "São Bento", walkMinutes: 12 },
    ],
    agentName: "Ирина",
    publishedAt: "2026-04-22",
  },
  {
    id: "irina-004",
    slug: "faro-family-townhouse-irina-004",
    mode: "rent",
    title: "Таунхаус для семьи у побережья",
    city: "Фару",
    district: "Montenegro",
    country: "Португалия",
    location: {
      addressLabel: "Montenegro, Faro, Portugal",
      latitude: 37.0314,
      longitude: -7.9421,
      googleMapsUrl: buildGoogleMapsUrl(37.0314, -7.9421),
    },
    priceAmount: 3100,
    priceLabel: "€3 100 / месяц",
    shortDescription:
      "3 спальни, закрытый двор и удобный выезд к школам, аэропорту и пляжам Алгарве.",
    fullDescription:
      "Семейный таунхаус с приватным двором и просторной кухней-гостиной. Хороший вариант для релокации или сезонной аренды на длительный срок. Район спокойный, с удобной дорожной связью и повседневной инфраструктурой.",
    bedrooms: 3,
    bathrooms: 3,
    areaM2: 172,
    imageUrl:
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["parking", "security", "terrace", "furnished"],
    details: {
      propertyType: "townhouse",
      usableAreaM2: 151,
      builtAreaM2: 172,
      floor: "Дом целиком",
      exterior: true,
      elevator: false,
      parkingSpaces: 2,
      storageRoom: true,
      builtInWardrobes: true,
      equippedKitchen: true,
      furnished: true,
      balconyCount: 1,
      terraceCount: 1,
      condition: "good",
      yearBuilt: 2017,
      heating: "heat_pump",
      accessibilityAdapted: false,
      orientation: ["юг"],
      energyRating: "B-",
      bathroomsFull: 3,
      guestBathrooms: 1,
      buildingFloors: 2,
      monthlyCondoFeeEur: 35,
    },
    transportAccess: [
      { mode: "bus", route: "16", stopName: "Montenegro Centro", walkMinutes: 5 },
      { mode: "bus", route: "14", stopName: "Aeroporto", walkMinutes: 9 },
      { mode: "train", route: "Regional Algarve", stopName: "Faro", walkMinutes: 17 },
    ],
    agentName: "Ирина",
    publishedAt: "2026-04-20",
  },
  {
    id: "irina-005",
    slug: "porto-garden-apartment-irina-005",
    mode: "sale",
    title: "Апартаменты с садом в Порту",
    city: "Порту",
    district: "Foz do Douro",
    country: "Португалия",
    location: {
      addressLabel: "Foz do Douro, Porto, Portugal",
      latitude: 41.1558,
      longitude: -8.6588,
      googleMapsUrl: buildGoogleMapsUrl(41.1558, -8.6588),
    },
    priceAmount: 820000,
    priceLabel: "€820 000",
    shortDescription:
      "3 спальни, приватный сад и тихая улица рядом с океаном и городской инфраструктурой.",
    fullDescription:
      "Просторные апартаменты с отдельным выходом в сад, хорошей инсоляцией и спокойной атмосферой района Foz do Douro. Подходят для семьи, которой важны близость к океану, школы и комфортный повседневный ритм.",
    bedrooms: 3,
    bathrooms: 2,
    areaM2: 146,
    imageUrl:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["city_center", "parking", "terrace", "furnished"],
    details: {
      propertyType: "apartment",
      usableAreaM2: 132,
      builtAreaM2: 146,
      plotAreaM2: 64,
      floor: "1 этаж",
      exterior: true,
      elevator: true,
      parkingSpaces: 1,
      storageRoom: true,
      builtInWardrobes: true,
      equippedKitchen: true,
      furnished: true,
      balconyCount: 0,
      terraceCount: 1,
      condition: "excellent",
      yearBuilt: 2019,
      heating: "central",
      accessibilityAdapted: true,
      orientation: ["запад", "север"],
      energyRating: "A",
      bathroomsFull: 2,
      buildingFloors: 5,
      monthlyCondoFeeEur: 120,
    },
    transportAccess: [
      { mode: "bus", route: "200", stopName: "Foz Igreja", walkMinutes: 4 },
      { mode: "tram", route: "1", stopName: "Passeio Alegre", walkMinutes: 7 },
      { mode: "bus", route: "500", stopName: "Castelo do Queijo", walkMinutes: 10 },
    ],
    taxProfile: {
      propertyTransferTaxRate: 0.058,
      stampDutyRate: 0.008,
      notaryEstimateRate: 0.01,
    },
    agentName: "Ирина",
    publishedAt: "2026-04-18",
  },
  {
    id: "irina-006",
    slug: "lagos-sea-view-penthouse-irina-006",
    mode: "sale",
    title: "Пентхаус с видом на море в Лагуше",
    city: "Лагуш",
    district: "Meia Praia",
    country: "Португалия",
    location: {
      addressLabel: "Meia Praia, Lagos, Portugal",
      latitude: 37.1179,
      longitude: -8.6462,
      googleMapsUrl: buildGoogleMapsUrl(37.1179, -8.6462),
    },
    priceAmount: 1290000,
    priceLabel: "€1 290 000",
    shortDescription:
      "2 спальни, панорамная терраса и открытый вид на побережье для курортной жизни или инвестиции.",
    fullDescription:
      "Пентхаус в современном комплексе рядом с пляжем Meia Praia. Большая терраса, много света и выразительный вид на море делают объект сильным вариантом как для личного проживания, так и для премиальной аренды.",
    bedrooms: 2,
    bathrooms: 2,
    areaM2: 132,
    imageUrl:
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["sea_view", "terrace", "pool", "security"],
    details: {
      propertyType: "penthouse",
      usableAreaM2: 121,
      builtAreaM2: 132,
      floor: "5 этаж",
      exterior: true,
      elevator: true,
      parkingSpaces: 2,
      storageRoom: true,
      builtInWardrobes: true,
      equippedKitchen: true,
      furnished: false,
      balconyCount: 0,
      terraceCount: 2,
      condition: "excellent",
      yearBuilt: 2020,
      heating: "heat_pump",
      accessibilityAdapted: true,
      orientation: ["юг", "восток"],
      energyRating: "A+",
      bathroomsFull: 2,
      buildingFloors: 5,
      monthlyCondoFeeEur: 210,
    },
    transportAccess: [
      { mode: "bus", route: "2", stopName: "Meia Praia", walkMinutes: 6 },
      { mode: "train", route: "Linha do Algarve", stopName: "Lagos", walkMinutes: 14 },
      { mode: "bus", route: "4", stopName: "Marina", walkMinutes: 9 },
    ],
    taxProfile: {
      propertyTransferTaxRate: 0.063,
      stampDutyRate: 0.008,
      notaryEstimateRate: 0.011,
    },
    agentName: "Ирина",
    publishedAt: "2026-04-17",
  },
  {
    id: "irina-007",
    slug: "braga-modern-flat-irina-007",
    mode: "rent",
    title: "Современная квартира в Браге",
    city: "Брага",
    district: "São Vicente",
    country: "Португалия",
    location: {
      addressLabel: "São Vicente, Braga, Portugal",
      latitude: 41.5504,
      longitude: -8.4195,
      googleMapsUrl: buildGoogleMapsUrl(41.5504, -8.4195),
    },
    priceAmount: 1850,
    priceLabel: "€1 850 / месяц",
    shortDescription:
      "2 спальни, свежий ремонт и удобная локация рядом с историческим центром и университетом.",
    fullDescription:
      "Квартира после обновления с хорошей отделкой, полноценной кухней и уютной гостиной. Подойдет для пары, семьи или специалиста, кому важны удобство города и спокойный жилой район Браги.",
    bedrooms: 2,
    bathrooms: 2,
    areaM2: 96,
    imageUrl:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["city_center", "furnished", "balcony"],
    details: {
      propertyType: "apartment",
      usableAreaM2: 88,
      builtAreaM2: 96,
      floor: "3 этаж",
      exterior: true,
      elevator: true,
      parkingSpaces: 0,
      storageRoom: false,
      builtInWardrobes: true,
      equippedKitchen: true,
      furnished: true,
      balconyCount: 1,
      terraceCount: 0,
      condition: "excellent",
      yearBuilt: 2016,
      heating: "electric",
      accessibilityAdapted: false,
      orientation: ["восток"],
      energyRating: "B",
      bathroomsFull: 2,
      buildingFloors: 6,
      monthlyCondoFeeEur: 65,
    },
    transportAccess: [
      { mode: "bus", route: "2", stopName: "São Vicente", walkMinutes: 3 },
      { mode: "bus", route: "24", stopName: "Avenida Central", walkMinutes: 7 },
      { mode: "train", route: "Braga Urban", stopName: "Braga", walkMinutes: 16 },
    ],
    agentName: "Ирина",
    publishedAt: "2026-04-16",
  },
  {
    id: "irina-008",
    slug: "coimbra-riverside-duplex-irina-008",
    mode: "rent",
    title: "Дуплекс у реки в Коимбре",
    city: "Коимбра",
    district: "Santa Clara",
    country: "Португалия",
    location: {
      addressLabel: "Santa Clara, Coimbra, Portugal",
      latitude: 40.1993,
      longitude: -8.4301,
      googleMapsUrl: buildGoogleMapsUrl(40.1993, -8.4301),
    },
    priceAmount: 2650,
    priceLabel: "€2 650 / месяц",
    shortDescription:
      "3 спальни, два уровня и терраса с открытым видом для комфортной долгосрочной аренды.",
    fullDescription:
      "Светлый дуплекс рядом с набережной Коимбры. На первом уровне расположена дневная зона, на втором приватный блок спален. Хороший вариант для семьи или арендаторов, которым нужен более редкий формат планировки.",
    bedrooms: 3,
    bathrooms: 2,
    areaM2: 154,
    imageUrl:
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["terrace", "furnished", "parking"],
    details: {
      propertyType: "duplex",
      usableAreaM2: 140,
      builtAreaM2: 154,
      floor: "4-5 этаж",
      exterior: true,
      elevator: true,
      parkingSpaces: 1,
      storageRoom: true,
      builtInWardrobes: true,
      equippedKitchen: true,
      furnished: true,
      balconyCount: 1,
      terraceCount: 1,
      condition: "good",
      yearBuilt: 2014,
      heating: "central",
      accessibilityAdapted: false,
      orientation: ["юг", "запад"],
      energyRating: "B-",
      bathroomsFull: 2,
      buildingFloors: 5,
      monthlyCondoFeeEur: 110,
    },
    transportAccess: [
      { mode: "bus", route: "7T", stopName: "Santa Clara", walkMinutes: 4 },
      { mode: "bus", route: "103", stopName: "Portugal dos Pequenitos", walkMinutes: 6 },
      { mode: "train", route: "Coimbra-A", stopName: "Coimbra-A", walkMinutes: 13 },
    ],
    agentName: "Ирина",
    publishedAt: "2026-04-15",
  },
  {
    id: "irina-009",
    slug: "sintra-ocean-view-land-irina-009",
    mode: "sale",
    title: "Участок с видом на океан в Синтре",
    city: "Синтра",
    district: "Azenhas do Mar",
    country: "Португалия",
    location: {
      addressLabel: "Azenhas do Mar, Sintra, Portugal",
      latitude: 38.8414,
      longitude: -9.4616,
      googleMapsUrl: buildGoogleMapsUrl(38.8414, -9.4616),
    },
    priceAmount: 420000,
    priceLabel: "€420 000",
    shortDescription:
      "Участок под строительство частной резиденции или камерного инвестиционного проекта с открытым видом на океан.",
    fullDescription:
      "Ровный участок рядом с побережьем Синтры. Подходит для проекта частного дома с видовой террасой или для аккуратной инвестиционной застройки в премиальной локации у океана.",
    bedrooms: 0,
    bathrooms: 0,
    areaM2: 960,
    imageUrl:
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["sea_view", "security"],
    details: {
      propertyType: "land",
      usableAreaM2: 960,
      builtAreaM2: 0,
      plotAreaM2: 960,
      exterior: false,
      elevator: false,
      parkingSpaces: 0,
      storageRoom: false,
      builtInWardrobes: false,
      equippedKitchen: false,
      furnished: false,
      balconyCount: 0,
      terraceCount: 0,
      condition: "good",
      yearBuilt: 0,
      heating: "electric",
      accessibilityAdapted: false,
      orientation: ["юг", "запад"],
      energyRating: "C",
      bathroomsFull: 0,
      buildingFloors: 0,
      monthlyCondoFeeEur: 0,
    },
    transportAccess: [
      { mode: "bus", route: "1253", stopName: "Azenhas do Mar", walkMinutes: 7 },
      { mode: "train", route: "Linha de Sintra", stopName: "Sintra", walkMinutes: 18 },
    ],
    taxProfile: {
      propertyTransferTaxRate: 0.065,
      stampDutyRate: 0.008,
      notaryEstimateRate: 0.011,
    },
    agentName: "Ирина",
    publishedAt: "2026-04-14",
  },
  {
    id: "irina-010",
    slug: "lisbon-room-for-rent-irina-010",
    mode: "rent",
    title: "Комната в Лиссабоне рядом с метро",
    city: "Лиссабон",
    district: "Alvalade",
    country: "Португалия",
    location: {
      addressLabel: "Alvalade, Lisbon, Portugal",
      latitude: 38.7481,
      longitude: -9.1456,
      googleMapsUrl: buildGoogleMapsUrl(38.7481, -9.1456),
    },
    priceAmount: 950,
    priceLabel: "€950 / месяц",
    shortDescription:
      "Комната с мебелью в аккуратной квартире, рядом метро и супермаркеты.",
    fullDescription:
      "Комната для долгосрочной аренды в ухоженной квартире в районе Alvalade. Подходит для студента или специалиста, кому важны транспорт, спокойный район и готовая инфраструктура рядом.",
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 18,
    imageUrl:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["city_center", "furnished", "balcony"],
    details: {
      propertyType: "room",
      usableAreaM2: 15,
      builtAreaM2: 18,
      floor: "3 этаж",
      exterior: true,
      elevator: true,
      parkingSpaces: 0,
      storageRoom: false,
      builtInWardrobes: true,
      equippedKitchen: true,
      furnished: true,
      balconyCount: 1,
      terraceCount: 0,
      condition: "good",
      yearBuilt: 2012,
      heating: "electric",
      accessibilityAdapted: false,
      orientation: ["восток"],
      energyRating: "B-",
      bathroomsFull: 1,
      buildingFloors: 6,
      monthlyCondoFeeEur: 0,
    },
    transportAccess: [
      { mode: "metro", route: "Verde", stopName: "Alvalade", walkMinutes: 4 },
      { mode: "bus", route: "736", stopName: "Avenida da Igreja", walkMinutes: 3 },
    ],
    agentName: "Ирина",
    publishedAt: "2026-04-13",
  },
  {
    id: "irina-011",
    slug: "porto-studio-rent-irina-011",
    mode: "rent",
    title: "Студия в Порту для долгосрочной аренды",
    city: "Порту",
    district: "Cedofeita",
    country: "Португалия",
    location: {
      addressLabel: "Cedofeita, Porto, Portugal",
      latitude: 41.1515,
      longitude: -8.6158,
      googleMapsUrl: buildGoogleMapsUrl(41.1515, -8.6158),
    },
    priceAmount: 1450,
    priceLabel: "€1 450 / месяц",
    shortDescription:
      "Компактная студия с хорошим светом, кухней и удобным доступом к центру Порту.",
    fullDescription:
      "Современная студия для аренды в районе Cedofeita. Хороший вариант для одного человека или пары, кому нужен компактный формат жилья, современная отделка и городская инфраструктура рядом.",
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 42,
    imageUrl:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["city_center", "furnished"],
    details: {
      propertyType: "studio",
      usableAreaM2: 38,
      builtAreaM2: 42,
      floor: "2 этаж",
      exterior: true,
      elevator: false,
      parkingSpaces: 0,
      storageRoom: false,
      builtInWardrobes: true,
      equippedKitchen: true,
      furnished: true,
      balconyCount: 0,
      terraceCount: 0,
      condition: "excellent",
      yearBuilt: 2021,
      heating: "heat_pump",
      accessibilityAdapted: false,
      orientation: ["юг"],
      energyRating: "A",
      bathroomsFull: 1,
      buildingFloors: 5,
      monthlyCondoFeeEur: 0,
    },
    transportAccess: [
      { mode: "bus", route: "201", stopName: "Cedofeita", walkMinutes: 3 },
      { mode: "metro", route: "D", stopName: "Lapa", walkMinutes: 8 },
    ],
    agentName: "Ирина",
    publishedAt: "2026-04-12",
  },
  {
    id: "irina-012",
    slug: "algarve-sea-plot-sale-irina-012",
    mode: "sale",
    title: "Ð£Ñ‡Ð°ÑÑ‚Ð¾Ðº Ð¿Ð¾Ð´ Ð²Ð¸Ð»Ð»Ñƒ Ð² ÐÐ»Ð³Ð°Ñ€Ð²Ðµ",
    city: "Ð›Ð°Ð³ÑƒÑˆ",
    district: "Praia da Luz",
    country: "ÐŸÐ¾Ñ€Ñ‚ÑƒÐ³Ð°Ð»Ð¸Ñ",
    location: {
      addressLabel: "Praia da Luz, Lagos, Portugal",
      latitude: 37.0894,
      longitude: -8.7281,
      googleMapsUrl: buildGoogleMapsUrl(37.0894, -8.7281),
    },
    priceAmount: 420000,
    priceLabel: "â‚¬420 000",
    shortDescription:
      "Ð£Ñ‡Ð°ÑÑ‚Ð¾Ðº Ñ Ð¾Ñ‚ÐºÑ€Ñ‹Ñ‚Ñ‹Ð¼ Ð²Ð¸Ð´Ð¾Ð¼ Ð¸ ÑƒÐ´Ð¾Ð±Ð½Ñ‹Ð¼ Ð¿Ð¾Ð´ÑŠÐµÐ·Ð´Ð¾Ð¼, Ð¿Ð¾Ð´Ñ…Ð¾Ð´Ð¸Ñ‚ Ð´Ð»Ñ Ð¿Ñ€Ð¾ÐµÐºÑ‚Ð° ÑÐ¾Ð²Ñ€ÐµÐ¼ÐµÐ½Ð½Ð¾Ð¹ Ð²Ð¸Ð»Ð»Ñ‹.",
    fullDescription:
      "ÐŸÑ€Ð¾ÑÑ‚Ð¾Ñ€Ð½Ñ‹Ð¹ ÑƒÑ‡Ð°ÑÑ‚Ð¾Ðº Ð² Ñ€Ð°Ð¹Ð¾Ð½Ðµ Praia da Luz Ñ ÑƒÐ´Ð¾Ð±Ð½Ñ‹Ð¼ Ð²Ñ‹ÐµÐ·Ð´Ð¾Ð¼ Ðº Ð¿Ð¾Ð±ÐµÑ€ÐµÐ¶ÑŒÑŽ Ð¸ Ð¸Ð½Ñ„Ñ€Ð°ÑÑ‚Ñ€ÑƒÐºÑ‚ÑƒÑ€Ðµ. Ð¥Ð¾Ñ€Ð¾ÑˆÐ¸Ð¹ Ð²Ð°Ñ€Ð¸Ð°Ð½Ñ‚ Ð´Ð»Ñ Ñ‡Ð°ÑÑ‚Ð½Ð¾Ð¹ Ñ€ÐµÐ·Ð¸Ð´ÐµÐ½Ñ†Ð¸Ð¸ Ð¸Ð»Ð¸ Ð¸Ð½Ð²ÐµÑÑ‚Ð¸Ñ†Ð¸Ð¾Ð½Ð½Ð¾Ð³Ð¾ Ð¿Ñ€Ð¾ÐµÐºÑ‚Ð° Ñ Ð²Ñ‹Ñ…Ð¾Ð´Ð¾Ð¼ Ð½Ð° Ð°Ð»Ð³Ð°Ñ€Ð²Ð¸Ð¹ÑÐºÐ¸Ð¹ Ñ€Ñ‹Ð½Ð¾Ðº Ð½ÐµÐ´Ð²Ð¸Ð¶Ð¸Ð¼Ð¾ÑÑ‚Ð¸.",
    bedrooms: 0,
    bathrooms: 0,
    areaM2: 1180,
    imageUrl:
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    imageGallery: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
    ],
    features: ["sea_view", "security"],
    details: {
      propertyType: "land",
      usableAreaM2: 1180,
      builtAreaM2: 0,
      plotAreaM2: 1180,
      exterior: false,
      elevator: false,
      parkingSpaces: 0,
      storageRoom: false,
      builtInWardrobes: false,
      equippedKitchen: false,
      furnished: false,
      balconyCount: 0,
      terraceCount: 0,
      condition: "new_build",
      yearBuilt: 0,
      heating: "none",
      accessibilityAdapted: false,
      orientation: ["ÑŽÐ³", "Ð·Ð°Ð¿Ð°Ð´"],
      energyRating: "A",
      bathroomsFull: 0,
      buildingFloors: 0,
      monthlyCondoFeeEur: 0,
    },
    transportAccess: [
      { mode: "bus", route: "4", stopName: "Praia da Luz Centro", walkMinutes: 6 },
      { mode: "train", route: "Linha do Algarve", stopName: "Lagos", walkMinutes: 14 },
    ],
    taxProfile: {
      propertyTransferTaxRate: 0.065,
      stampDutyRate: 0.008,
      notaryEstimateRate: 0.012,
    },
    agentName: "Ð˜Ñ€Ð¸Ð½Ð°",
    publishedAt: "2026-04-11",
  },
];

export function getFeatureLabel(feature: ListingFeature): string {
  return featureLabels[feature];
}

export function getPropertyBySlug(slug: string): PropertyListing | undefined {
  return propertyListings.find((property) => property.slug === slug);
}

export function getPropertiesByMode(mode: ListingMode): PropertyListing[] {
  return propertyListings.filter((property) => property.mode === mode);
}
